applicationName: life_jigsaw
serverPort: 5026
database:
    url: jdbc:sqlite:./life_jigsaw.db
    driver: org.sqlite.JDBC
    username: 
    password: 
swaggerEnable: true

logging:
    level:
        root: INFO
